#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const NeoWCAutoDeviceLoginKey;
FOUNDATION_EXPORT NSString *const NeoWCAutoGameAuthorizeKey;
FOUNDATION_EXPORT NSString *const NeoWCMomentsDoubleTapLikeKey;
FOUNDATION_EXPORT NSString *const NeoWCMomentsQuickCommentKey;
FOUNDATION_EXPORT NSString *const NeoWCGameSelectorKey;
FOUNDATION_EXPORT NSString *const NeoWCStepOverrideEnabledKey;
FOUNDATION_EXPORT NSString *const NeoWCStepCountKey;
FOUNDATION_EXPORT NSString *const NeoWCStepCountDateKey;
FOUNDATION_EXPORT NSString *const NeoWCAdBlockerKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeNotifySenderKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeLocalTemplateKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeReplyTemplateKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeTimeFilterKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokePromptStyleKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeSideTextKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeSideOffsetXKey;
FOUNDATION_EXPORT NSString *const NeoWCAntiRevokeSideOffsetYKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureEnabledKey;
FOUNDATION_EXPORT NSString *const NeoWCImageEditQuickSendEnabledKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureIncludeChromeKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureHideMemberNamesKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureShowBackgroundKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureCloseAfterShareKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureCropTopPointsKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureShowChatNameKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureShowTimestampKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureWatermarkTextKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureWatermarkStyleKey;
FOUNDATION_EXPORT NSString *const NeoWCChatCaptureWatermarkOpacityKey;
FOUNDATION_EXPORT NSString *const NeoWCEnhancementDidChangeNotification;

FOUNDATION_EXPORT BOOL NeoWCEnhancementEnabled(NSString *key);
